[build]
  publish = "public"
  command = "hugo --gc --minify"

[[edge_functions]]
  path = ".netlify/functions/hf_proxy"
  function = "hf_proxy"
  

[context.production.environment]
  HUGO_VERSION = "0.149.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

